name: Deploy to Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to Server
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.SSH_P }}

      - name: SSH into Server and Deploy
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_U }}@${{ secrets.SSH_A }} -p ${{ secrets.SSH_PORT }} "
          cd ${{ secrets.WORK_DIR }} || { echo 'Directory not found'; exit 1; }
          echo 'Current directory:' && pwd
          git config --global --add safe.directory ${{ secrets.WORK_DIR }}
          git pull origin main
          git reset --hard origin/main
          systemctl --user restart slavikd
          "